title: 'Pasta - Simply Delicious'
description: 'Pasta is a tiny SASS file that provides a great starting place for web projects. It combines a handy reset and light styling for common web elements, yummy.'
keywords: 'pasta, css, html, responsive, sass, minimal, jared pendergraft'
baseurl: "/pasta"
url: "http://jaredpdesigns.github.io/pasta"
exclude: ["README.md"]
source: src
destination: docs

# Build settings
markdown: kramdown
sass:
  sass_dir: pasta
  style: compressed
highlighter: none

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  
gems:
- jekyll-autoprefixer